// Demo listings: photography and fictional catalogue details are for testing.
const rows = [
  [
    "The Sunday Chair",
    "living",
    18900,
    8,
    "forme-living.jpg",
    "Rust lounge chair in a sunlit room",
    "A generous upholstered lounge chair for reading and slower mornings. Includes one chair; the table and room accessories are not included.",
    "Upholstery and wood",
    "One lounge chair",
  ],
  [
    "Halo Table Light",
    "workspace",
    3490,
    18,
    "lamp.jpg",
    "Table lamp with a white fabric shade",
    "A softly shaded table lamp for bedside reading and evening work. Includes one lamp; other furnishings in the photograph are styling props.",
    "Fabric shade and ceramic base",
    "One table lamp",
  ],
  [
    "Daybreak Cup & Saucer",
    "objects",
    890,
    32,
    "cup.jpg",
    "White cup and matching saucer",
    "A simple porcelain cup with a comfortable handle and a matching saucer. Made for everyday coffee and tea.",
    "Porcelain",
    "One cup and one saucer",
  ],
  [
    "The Daily Carry",
    "everyday",
    4290,
    14,
    "bag.jpg",
    "Brown everyday leather bag",
    "A warm brown bag with room for daily essentials. Includes one bag; surface variation is part of its leather finish.",
    "Leather",
    "One bag",
  ],
  [
    "Studio Headphones",
    "workspace",
    2990,
    20,
    "headphones.jpg",
    "Over-ear headphones",
    "A cushioned pair of over-ear headphones for music, study and focused afternoons. Includes one pair of wired headphones.",
    "Padded headband and ear cups",
    "One pair of headphones",
  ],
  [
    "The Reading Chair",
    "living",
    14900,
    6,
    "forme-studio.jpg",
    "Dark wood chair beside a window",
    "A dark wood accent chair with upholstered seating. A comfortable corner for an unhurried chapter; surrounding furnishings are not included.",
    "Wood and upholstery",
    "One accent chair",
  ],
  [
    "Ripple Ceramic Vase",
    "living",
    1590,
    16,
    "seed-vase.jpg",
    "Sculpted white vase on a table",
    "A sculptural white vase with a rounded profile. Display it on its own or with dried stems. Flowers, books and candleholders are not included.",
    "Ceramic",
    "One vase",
  ],
  [
    "Green Corner Planter",
    "living",
    1890,
    12,
    "seed-plant.jpg",
    "Green indoor plant in a pale planter",
    "A leafy indoor plant in a pale decorative pot. Place in bright indirect light and water when the top layer of soil feels dry.",
    "Live plant and decorative pot",
    "One plant with pot",
  ],
  [
    "Soft Stripe Cushion Pair",
    "living",
    2190,
    24,
    "seed-cushions.jpg",
    "Textured cushions on a sofa",
    "A pair of textured cushions for an armchair or sofa. Neutral colours and a striped detail work with an everyday living space. The sofa is not included.",
    "Woven fabric covers",
    "Two filled cushions",
  ],
  [
    "Frost Ceramic Bowl",
    "objects",
    1190,
    28,
    "seed-bowl.jpg",
    "Pale glazed ceramic bowl",
    "A softly glazed bowl for breakfast, small meals or a side salad. Includes one bowl with a subtly textured exterior.",
    "Glazed ceramic",
    "One bowl",
  ],
  [
    "Pour & Share Set",
    "objects",
    2490,
    10,
    "seed-serving-set.jpg",
    "Ceramic bottle and two cups",
    "A ceramic pouring bottle with two matching cups. An understated three-piece set for a shared drink at the table.",
    "Glazed ceramic",
    "One bottle and two cups",
  ],
  [
    "Nesting Table Bowls",
    "objects",
    2790,
    15,
    "seed-bowl-set.jpg",
    "A collection of pale ceramic bowls",
    "A nesting bowl set for serving and everyday meals. Soft pale glazes and simple shapes keep the table easy to arrange.",
    "Glazed ceramic",
    "One nesting bowl set",
  ],
  [
    "Forest Jar Candle",
    "objects",
    990,
    30,
    "seed-candle.jpg",
    "Lit candle in a glass jar",
    "A candle in a clear glass jar for a quiet evening at home. Place on a heat-resistant surface and never leave a burning candle unattended.",
    "Wax and glass",
    "One jar candle",
  ],
  [
    "The Daily Notebook",
    "workspace",
    490,
    45,
    "seed-notebook.jpg",
    "Open notebook with lined pages",
    "A lined notebook for plans, lists and first drafts. An uncomplicated place to keep the day on paper.",
    "Paper",
    "One lined notebook",
  ],
  [
    "Quiet Hours Desk Clock",
    "workspace",
    1490,
    18,
    "seed-clock.jpg",
    "Cream twin-bell alarm clock",
    "A compact analogue clock with a clear face and twin-bell profile. Includes one clock; the plant and other accessories are not included.",
    "Metal and glass",
    "One desk clock",
  ],
  [
    "The Work Table",
    "workspace",
    12900,
    5,
    "desk.jpg",
    "Wooden work table in a study setting",
    "A work table with room for a notebook, lamp and daily tasks. Includes the table only; lighting, seating and accessories are not included.",
    "Wood",
    "One work table",
  ],
  [
    "Rather Be Home Tote",
    "everyday",
    790,
    35,
    "seed-tote.jpg",
    "Natural fabric tote with a red printed message",
    "A roomy natural-colour tote with a playful printed message. Long handles make it easy to carry a few everyday essentials.",
    "Cotton canvas",
    "One printed tote",
  ],
  [
    "Clear Day Travel Bottle",
    "everyday",
    1290,
    22,
    "seed-bottle.jpg",
    "Clear travel bottle with a metallic cap",
    "A clear reusable bottle with a metallic cap and carry loop. Take it to a desk or pack it for a short outing. Hand-wash before first use.",
    "Glass with metal accents",
    "One bottle",
  ],
  [
    "Weekend Sunglasses",
    "everyday",
    1690,
    17,
    "seed-sunglasses.jpg",
    "Sunglasses photographed at the beach",
    "A pair of casual sunglasses with a simple frame for weekend outfits. Includes one pair; the photograph shows the frame style.",
    "Acetate-style frame",
    "One pair of sunglasses",
  ],
  [
    "The Travel Pouch",
    "everyday",
    2290,
    19,
    "seed-pouch.jpg",
    "Brown leather pouch on a wooden table",
    "A compact brown leather pouch with a zipper and wrist strap for keys, cards and travel essentials. The gallery shows the same pouch from several views.",
    "Leather",
    "One zipped pouch",
  ],
];
const catalogue = rows.map(
  (
    [name, category, price, stock, file, alt, description, material, included],
    index,
  ) => ({
    name,
    category,
    price,
    stock,
    description,
    vendorIndex: index % 2,
    specifications: [
      { label: "Material", value: material },
      { label: "Includes", value: included },
      {
        label: "Care",
        value:
          category === "living"
            ? "Dust gently; follow the supplied care instructions."
            : "Clean gently and store in a dry place.",
      },
    ],
    photos: [{ file, alt }],
  }),
);
catalogue
  .at(-1)
  .photos.push(
    { file: "seed-pouch-side.jpg", alt: "Travel pouch alternate view" },
    { file: "seed-pouch-detail.jpg", alt: "Travel pouch close detail" },
  );
const accounts = [
  { email: "hello@forme.demo", name: "Alex Morgan", role: "CUSTOMER" },
  { email: "studio@forme.demo", name: "Form & Field", role: "VENDOR" },
  { email: "objects@forme.demo", name: "Everyday Studio", role: "VENDOR" },
  { email: "admin@forme.demo", name: "FORME Admin", role: "ADMIN" },
];
const categories = [
  { slug: "living", name: "For the home" },
  { slug: "objects", name: "Everyday objects" },
  { slug: "workspace", name: "For your workspace" },
  { slug: "everyday", name: "On the go" },
];
module.exports = { catalogue, accounts, categories };
